# Generated by Django 4.2.16 on 2025-07-29 13:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_rename_shipping_option_order_roasting_option_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuineaAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Ex: 123 près de la mosquée Diaouné, en face du marché', verbose_name="Description de l'adresse")),
                ('landmark', models.CharField(blank=True, help_text='Ex: Mosquée, École, Marché, etc.', max_length=200, verbose_name='Point de repère')),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(7.0), django.core.validators.MaxValueValidator(13.0)], verbose_name='Latitude')),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-15.0), django.core.validators.MaxValueValidator(-7.0)], verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'En attente de validation'), ('validated', 'Validée'), ('rejected', 'Rejetée')], default='pending', max_length=20)),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'utilisations")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='addresses/photos/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adresse guinéenne',
                'verbose_name_plural': 'Adresses guinéennes',
                'ordering': ['-usage_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuineaPrefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la préfecture')),
                ('code', models.CharField(max_length=10, verbose_name='Code préfecture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Préfecture',
                'verbose_name_plural': 'Préfectures',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GuineaRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la région')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code région')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Région',
                'verbose_name_plural': 'Régions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('description', models.TextField(help_text='Décrivez précisément votre localisation', verbose_name='Description personnalisée')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_locations/')),
                ('photo_latitude', models.FloatField(blank=True, null=True)),
                ('photo_longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('guinea_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.guineaaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Localisation utilisateur',
                'verbose_name_plural': 'Localisations utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuineaQuartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du quartier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartiers', to='store.guineaprefecture')),
            ],
            options={
                'verbose_name': 'Quartier',
                'verbose_name_plural': 'Quartiers',
                'ordering': ['name'],
                'unique_together': {('prefecture', 'name')},
            },
        ),
        migrations.AddField(
            model_name='guineaprefecture',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefectures', to='store.guinearegion'),
        ),
        migrations.AddField(
            model_name='guineaaddress',
            name='prefecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='store.guineaprefecture'),
        ),
        migrations.AddField(
            model_name='guineaaddress',
            name='quartier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='store.guineaquartier'),
        ),
        migrations.AddField(
            model_name='guineaaddress',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='store.guinearegion'),
        ),
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_instructions', models.TextField(help_text='Comment accéder à cette adresse (étage, porte, etc.)', verbose_name="Instructions d'accès")),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Téléphone de contact')),
                ('is_default', models.BooleanField(default=False, verbose_name='Adresse par défaut')),
                ('user_location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_info', to='store.userlocation')),
            ],
            options={
                'verbose_name': 'Adresse de livraison',
                'verbose_name_plural': 'Adresses de livraison',
            },
        ),
        migrations.AlterUniqueTogether(
            name='guineaprefecture',
            unique_together={('region', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='guineaaddress',
            unique_together={('latitude', 'longitude')},
        ),
    ]
