# Generated by Django 4.2.16 on 2025-07-29 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_alter_promocode_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 28, 13, 6, 1, 37704, tzinfo=datetime.timezone.utc)),
        ),
    ]
